UI connection
NicolasBourdin88/PokemonCardMobileApp pull request #13
Opened 2024-11-07 09:53 UTC by suuuullivan

2024-11-07 11:18 UTC, NicolasBourdin88 requested changes
Dose

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/build.gradle.kts
> +    implementation(libs.firebase.firestore)
You should put Firebase libs into a category

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/data/model/PokemonCellProfil.kt
> +enum class PokemonCellProfil(
```suggestion
enum class PokemonCellProfile(
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/data/model/pokemonCard/database/RemoteKeyDao.kt
You forgot to delete this file

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/data/model/userModel/UserEntity.kt
Rename your file to the name of your class

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/data/model/userModel/database/PokemonCellProfilConverter.kt
Use 'Profile' instead of 'Profil'

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/navigation/AppNavigation.kt
> +
Remove useless break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/navigation/AppNavigation.kt
> +            if (isPortrait && !isOnUserScreen(navBackStackEntry)) BottomBarNavigation(
Use block if instead of place it on one line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/navigation/AppNavigation.kt
> +                                        .padding(top = 54.dp, end = 16.dp)
Use 'Padding' class to keep same dimension everywhere

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/navigation/AppNavigation.kt
> +                                modifier = Modifier.padding(top = 54.dp, end = 16.dp),
Use 'Padding' class to keep same dimension everywhere

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/navigation/AppNavigation.kt
> +            if (!isPortrait && !isOnUserScreen(navBackStackEntry)) RailBarNavigation(
Same here use block if

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/navigation/NavItems.kt
> +
Remove useless break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/navigation/NavItems.kt
> +
Same here remove break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/navigation/NavItems.kt
> +
Remove break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/navigation/NavItems.kt
> +
Remove break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/Splashscreen.kt
> +const val SPLASH_SCREEN_DURATION: Long = 0L
Discard this diff.

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/authentification/AuthViewModel.kt
> +import androidx.compose.runtime.mutableStateOf
Remove the useless import `ctrl alt l`
`

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/authentification/AuthViewModel.kt
> +                println("test1011 All profiles in DB: $allProfiles")
Remove print

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/authentification/AuthViewModel.kt
> +            println("test1011 userprofil : "+userProfile);
Remove print

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/authentification/AuthViewModel.kt
> +                println("test1011 AuthViewModel: User profile loaded: ${it.pokemonCell},${it.pokemonCell.pokemonCellImage},${it.pokemonCell.name},${it.pokemonCell.ordinal}")
Remove print

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/authentification/AuthViewModel.kt
> +            userProfile?.let {
put let on one line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +        WelcomeBackText()
Remove all break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +        // Utilisation de CustomTextField pour le mail utilisateur
Remove useless comment

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +        // Utilisation de CustomTextField pour le mot de passe
Remove useless comment

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +        CustomTextField(
Use the correct font

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +        CustomTextField(
Use the correct font

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +        OrView()
I don't think `OrView()` is a good name

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +        GoogleSigninView()
```suggestion
        GoogleSignInView()
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +        SignupView(onSuccess, navController)
```suggestion
        SignUpView(onSuccess, navController)
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +
Remove break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +
Remove break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +fun PikachuWithCircle() {
I think something like `NoProfileSelectedIllustration` should be better

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +fun PikachuWithCircle() {
Put this code in Utils, I think all the logic corresponding only to Connexion and Inscription should be in a special file other than Utils

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +                }
```suggestion
            modifier = Modifier.graphicsLayer {
                scaleX = -1f
                translationY = 90f
                translationX = -22f
            }
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +        )
```suggestion
           Text(
            text = stringResource(id = R.string.welcome_back),
            fontSize = 36.sp,
            fontFamily = fontFamilyAvenir,
            fontWeight = FontWeight.Normal,
        )

        Text(
            text = stringResource(id = R.string.login_text),
            fontSize = 16.sp,
            fontFamily = fontFamilyAvenir,
            modifier = Modifier.padding(bottom = Padding.MEDIUM.dp)
        )
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +
Remove this breakline

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +            .padding(top = 30.dp)
Use correct padding

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +                }
```suggestion
                if (success) onSuccess()
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +            },
?

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +fun GoogleSigninView() {
```suggestion
fun GoogleSignInView() {
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +                .padding(end = 16.dp)
Use correct padding

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +fun SignupView(onSuccess: () -> Unit, navController: NavHostController) {
```suggestion
fun SignUpView(onSuccess: () -> Unit, navController: NavHostController) {
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +            modifier = Modifier.padding(end = 8.dp),
Use correct padding

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +    val isUserLoggedIn: State<Boolean> = _isUserLoggedIn
Remove this

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +
Remove this

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +    private val firestore: FirebaseFirestore = FirebaseFirestore.getInstance()
val should be declared on top of the file

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +            _errorConnectionMessage.value = "Les champs email et mot de passe ne peuvent pas être vides."
Should be in a `string.xml` and should not be in French

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +                    // Vérifie si l'utilisateur est déjà dans la base de données locale
Remove comment

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +                            // Si l'utilisateur n'est pas trouvé localement, récupère depuis Firestore
Remove comment

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +                            // L'utilisateur est déjà dans la base de données locale
Remove comment

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +        firestore.collection("users").document(userId).get()
users should be a `const val` inside companion

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +                    val profileImageId = document.getString("profileImageId")
Same here, should be a const val

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +                        _errorConnectionMessage.value = "Erreur : L'image de profil n'est pas valide."
Should be in English and in string.xml

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +                    _errorConnectionMessage.value = "Erreur : Profil utilisateur non trouvé dans Firestore."
Should be in English and in string.xml

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
> +                _errorConnectionMessage.value = "Erreur lors de la récupération depuis Firestore : ${e.message}"
Should be in English and in string.xml

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionViewModel.kt
Please use refractor, this should be a reflex

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/AuthenticationNavigation.kt
> +        }
```suggestion
        composable<AuthenticationNavigation.SignInDestination> {
            ConnectionScreen(
                navController,
                viewModel = connectionViewModel,
                onSuccess = {
                    back.invoke()
                }
            )
        }
        composable<AuthenticationNavigation.SignUpDestination> {
            InscriptionScreen(
                navController,
                viewModel = inscriptionViewModel,
                onSuccess = {
                    back.invoke()
                }
            )
        }
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +fun InscriptionScreen(
Should be rename `SignUp`

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +    LocalContext.current
Remove this

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +        PikachuWithButtonPlus(viewModel, { viewModel.toggleBottomSheet() })
Rename this function

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +        // Utilisation de CustomTextField pour le mail utilisateur
Remove this comment

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +        // Utilisation de CustomTextField pour le mot de passe
Remove this comment

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +        // Utilisation de CustomTextField pour la confirmation du mot de passe
Remove this comment

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +                modifier = Modifier.padding(horizontal = Padding.HUGE.dp, vertical = 0.dp)
It is 0.dp by default, remove this

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +            }
```suggestion
            if (isSuccess) onSuccess()
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +fun BottomBar(viewModel: InscriptionViewModel) {
It's a bottom sheet not a bottom bar, rename this

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +                columns = GridCells.Fixed(3),
maybe it should not be Fixel but Adaptative so the Bottom Sheet could adapt to the size of the screen

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +                }
```suggestion
                items(PokemonCellProfil.entries) { profile ->
                    ImagePokemon(
                        pokemonCellProfil = profile,
                        onClick = { viewModel.onImageSelected(profile) }
                    )
                }
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +        // Bouton "+" pour ouvrir la Bottom Sheet
Remove this comment

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +fun ButtonSignup(viewModel: InscriptionViewModel, onResult: (Boolean) -> Unit) {
Rename this

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +            .padding(top = 32.dp),
Use correct padding

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +            },
?

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +                .padding(end = 16.dp)
Add pading

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +            modifier = Modifier.padding(end = 8.dp),
Use correct padding

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionViewModel.kt
> +    val isUserLoggedIn: State<Boolean> = _isUserLoggedIn
Remove this unused

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionViewModel.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionViewModel.kt
> +    fun onImageSelected(pokemonCellProfil: PokemonCellProfil) {
rename profil to profile

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionViewModel.kt
> +                println("Utilisateur enregistré avec l'ID de l'image de profil dans Firestore")
Remove this print

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionViewModel.kt
> +                println("Erreur lors de l'enregistrement de l'utilisateur : ${e.message}")
Remove this print

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionViewModel.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/user/UserScreen.kt
> +    }
Useless column

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/user/UserViewModel.kt
Remove this file

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/theme/Color.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/utils/UiUtils.kt
> +
Remove this break line

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/utils/UiUtils.kt
> +    val visualTransformation = if (isPasswordField) PasswordVisualTransformation() else VisualTransformation.None
```suggestion
    val visualTransformation = if (isPasswordField) {
        PasswordVisualTransformation()
    } else {
        VisualTransformation.None
    }
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/utils/UiUtils.kt
> +                },
```suggestion
        label = {
            Text(
                text = label,
                color = MaterialTheme.colorScheme.onPrimary
            )
        },
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/utils/UiUtils.kt
> +            )
```suggestion
            Icon(
                painter = painterResource(id = leadingIconRes),
                contentDescription = label,
                modifier = Modifier
                    .size(27.dp)
                    .offset(y = (-4).dp),
                tint = MaterialTheme.colorScheme.onPrimary
            )
```

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/utils/UiUtils.kt
> +fun OrView() {
Find another name to this and should not be inside Utils

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/utils/UiUtils.kt
Please use refractor

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/res/drawable/ic_arrowleft.xml
Rename to ic_arrow_left and refractor

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/res/drawable/ic_google.xml
Refractor

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/res/drawable/ic_password.xml
> +        android:fillType="evenOdd"
Useless fillType

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/res/drawable/ic_plus.xml
Refractor

2024-11-07 11:18 UTC, NicolasBourdin88 commented on app/src/main/res/drawable/ic_user.xml
Refractor

2024-11-07 11:18 UTC, NicolasBourdin88 commented on build.gradle.kts
> +
Remove this breakline

2024-11-15 10:17 UTC, suuuullivan commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +fun PikachuWithCircle() {
they do not have the same logic and style

2024-11-15 10:29 UTC, suuuullivan commented on app/src/main/java/com/example/pokemonultimate/ui/screens/connection/ConnectionScreen.kt
> +            },
it will soon serve

2024-11-15 12:13 UTC, suuuullivan commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionScreen.kt
> +            },
it will soon serve

2024-11-15 12:18 UTC, suuuullivan commented on app/src/main/java/com/example/pokemonultimate/ui/screens/user/UserViewModel.kt
why ? It will be used in the next feature

2024-11-17 19:17 UTC, NicolasBourdin88 requested changes

2024-11-17 19:17 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/data/model/userModel/database/PokemonCellProfileConverter.kt
> +    fun fromPokemonCellProfile(profil: PokemonCellProfile): String {
```suggestion
    fun fromPokemonCellProfile(profile: PokemonCellProfile): String {
```

2024-11-17 19:17 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/data/model/userModel/database/PokemonCellProfileConverter.kt
> +        return profil.name
```suggestion
        return profile.name
```

2024-11-17 19:17 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/data/utils/Utils.kt
Rename this to UserUtils

2024-11-17 19:17 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/authentification/AuthViewModel.kt
> +) : ViewModel() {
Could be on one line

2024-11-17 19:17 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/AuthenticationNavigation.kt
> +    back: () -> Unit,
Rename this to 'onSuccess' or whatever make sense

2024-11-17 19:17 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/inscription/InscriptionViewModel.kt
> +) : ViewModel() {
Same here, put this on one line

2024-11-17 19:17 UTC, NicolasBourdin88 commented on app/src/main/java/com/example/pokemonultimate/ui/screens/user/UserScreen.kt
> +}
Event if it's just for test please respect indentation

```suggestion
@Composable
fun UserScreen() {
    Text("page user")
}
```

2024-11-17 21:05 UTC, NicolasBourdin88 approved these changes

2024-11-17 21:06 UTC, merged